### ISSUE TITLE
Extra semicolons in include/log4cxx/pattern/patternconverter.h

### ISSUE THREAD

**Issue by timcoleman** [apache/logging-log4cxx#179]
When compiled with -Wpedantic, g++ complains of extra semicolons in include/log4cxx/pattern/patternconverter.h in this section:

```
		DECLARE_LOG4CXX_PATTERN(PatternConverter);
		BEGIN_LOG4CXX_CAST_MAP();
		LOG4CXX_CAST_ENTRY(PatternConverter);
		END_LOG4CXX_CAST_MAP();
```

since the defines already include semicolons.

**Comment by rm5248** [comment]
Note: `-Wpedantic` also leads to other issues with the `LOG4CXX_INSTANTIATE_EXPORTED_PTR` macro - see [this comment](https://github.com/apache/logging-log4cxx/issues/177#issuecomment-1383078063) for more information.

**Comment by timcoleman** [comment]
Is that when compiling log4cxx? The warning I got was actually from including the header into my project that uses log4cxx. Sent from my iPhoneOn Jan 22, 2023, at 12:20 PM, Robert Middleton ***@***.***> wrote:﻿
Note: -Wpedantic also leads to other issues with the LOG4CXX_INSTANTIATE_EXPORTED_PTR macro - see this comment for more information.

**Comment by rm5248** [comment]
Yes, that is when compiling log4cxx with `-Wpedantic`.
