### ISSUE TITLE
SetThreadDescription and GetThreadDescription are not properly linked on Windows

### ISSUE THREAD

**Issue by timcoleman** [apache/logging-log4cxx#180]
In order to be used on Windows Server, the SetThreadDescription() and GetThreadDescription() functions need to be linked at run time, instead of at load time.

The code as implemented works on Windows 10 (and I assume on Windows 11), but fails on Windows Server (I have tested 2016, but not any other Server versions).

I have worked around this issue by disabling the symbol checks in CMakeLists.txt.

**Comment by swebb2066** [comment]
Could you tell me if the windows_server_issue branch resolves this issue on your Windows server version please?

**Comment by timcoleman** [comment]
Yes, I built it and it is working for me. Logs are being written, and 
the dependency walker doesn't show a missing dependency anymore.

Thanks,

Tim

------ Original Message ------
From "Stephen Webb" ***@***.***>
To "apache/logging-log4cxx" ***@***.***>
Cc "timcoleman" ***@***.***>; "Author" 
***@***.***>
Date 1/19/2023 2:02:19 AM
Subject Re: [apache/logging-log4cxx] SetThreadDescription and 
GetThreadDescription are not properly linked on Windows (Issue #180)

**Comment by timcoleman** [comment]
Hang on. I still think the code looks good, but I might have goofed something. Not enough coffee yet.

**Comment by timcoleman** [comment]
This bit in threadutility.cpp causes an error:

#if LOG4CXX_HAS_SETTHREADDESCRIPTION
	#include <windows.h>
	#include <processthreadsapi.h>
#endif

Aside from that, it seems good.

**Comment by rm5248** [comment]
Note for future reference: this is a problem on older systems.  According to the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription#remarks):

> Windows Server 2016, Windows 10 LTSB 2016 and Windows 10 version 1607: SetThreadDescription is only available by [Run Time Dynamic Linking](https://learn.microsoft.com/en-us/windows/win32/dlls/using-run-time-dynamic-linking) in KernelBase.dll.

Newer versions of Windows don't have this same limitation it seems, explaining why the builds on the github runners have never encountered this issue.

**Comment by swebb2066** [comment]
See PR #181
