### ISSUE TITLE
Error when Cross-compiling Log4CXX library for Linux Arm Cortex A9

### ISSUE THREAD

**Issue by Zaoui-Douaa** [apache/logging-log4cxx#209]
I'm trying to cross compile the log4cxx lib for an Linux-Arm-Cortex-A9

1. I installed a folder from git about Linux-Arm-Cortex-A9   "https://github.com/Christopher83/arm-cortex_a9-linux-gnueabihf-linaro_4.9"      and  I used it directly without doing a build in my pc because i don't know how  . 
2. Downloading and extracting source code of Log4CXX     "apache-log4cxx-1.0.0"
        
![Capt](https://user-images.githubusercontent.com/124036995/235287806-a71c06dd-432f-44b8-b29c-c85ebd9127a3.png)
  

- I need to compile it, it's very important for me because it's for my final project, otherwise I will change all the code to use Poco instead of log4cxx.   
I used log4cxx for the LOG message in my shared library .

**Comment by ams-tschoening** [comment]
Look at the error message, it has nothing to do with log4cxx itself, but whatever `arm-cortex_a9-linux-gnueabihf-linaro_4.9` is simply doesn't work properly in your setup. So you should ask that project about to properly setup that thing instead.

**Comment by Zaoui-Douaa** [comment]
i didn't understand you

**Comment by Zaoui-Douaa** [comment]
i already compile Poco and OpenSSl with Linux-Arm-Cortex-A9 and it's work

**Comment by ams-tschoening** [comment]
Might be, but without further details about how your are doing that for those projects it doesn't mean too much about this error message. Look at the error message, it's not coming from log4cxx itself and it's not mentioning any log4cxx file. Instead, the source is withing `arm-cortex_a9-linux-gnueabihf-linaro_4.9`: Seems to me like g++ bundled with that repo is trying to load `liblto_plugin.so` of that repo and that fails. that file seems to be a symlink to [liblto_plugin.so.0.0.0](https://github.com/Christopher83/arm-cortex_a9-linux-gnueabihf-linaro_4.9/blob/master/libexec/gcc/arm-cortex_a9-linux-gnueabihf/4.9.4/liblto_plugin.so.0.0.0), so you should have a further look at if that file makes sense or whatever. It might as well be that this file is not used in your other builds for some reason.

Anyway, I don't see any concrete relationship to some problem in log4cxx currently.

**Comment by Zaoui-Douaa** [comment]
so i should do to compile log4cxx with linux arm cortex a9  ?

**Comment by rm5248** [comment]
Your compiler is not working.  This is a problem with how your environment is setup.  Unfortunately we are not able to help you with your environment setup, as that is something that is very specific to your system and how you cross-compile code.

**Comment by swebb2066** [comment]
To cross compile using cmake you need to create a tool chain file and provide the file to cmake using the [CMAKE_TOOLCHAIN_FILE](https://cmake.org/cmake/help/latest/envvar/CMAKE_TOOLCHAIN_FILE.html#envvar:CMAKE_TOOLCHAIN_FILE) cmake parameter.

Please refer to [the cmake documentation](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Cross%20Compiling%20With%20CMake.html)
