### ISSUE TITLE
Create basic documentation on using Log4cxx in your projects

### ISSUE THREAD

**Issue by rm5248** [apache/logging-log4cxx#229]
There is currently some information in the documentation about how to use in your projects, but there's nothing along the lines of "copy and paste this into your buildsystem."

Perhaps adding a standalone project into the examples folder would be good.

**Comment by swebb2066** [comment]
I would like to make a start on this. Having just answered a stackoverflow question from a new C++ user using make (: I can see the urgent need.

I suggest a per package manager example. I can start with a conan example. Do you have a perference for what the actual C++ should do?

**Comment by rm5248** [comment]
I was thinking that we just need some pages on the website, I don't think an actual example is needed(although it could be useful).  My thought was something like the following:

To use with CMake, add the following:
```
find_package(log4cxx)

...
target_link_libraries(target PRIVATE log4cxx::log4cxx)
```

To use with CMake using pkg-config, add the following:
```
find_package(PkgConfig)
pkg_check_modules( log4cxx REQUIRED liblog4cxx )
...
target_link_libraries(target PRIVATE ${log4cxx_LIBRARIES})
```

To use with vcpkg, add the following to your vcpkg.json:
```
"dependencies": [
    {
      "name": "log4cxx",
      "version>=": "1.0.0#6"
    }
 }
```

Here's a few possible examples we could add:

- CMake
- CMake with pkgconfig
- CMake with Externalproject
- Meson
- vcpkg
- conan
- autotools

**Comment by swebb2066** [comment]
As with most things a think would be a good idea, [it has already been done](https://ilyas-hamadouche.medium.com/c-package-management-with-conan-introduction-8c7bd928c009)
