### ISSUE TITLE
Ability to remove a HierarchyEventListener?

### ISSUE THREAD

**Issue by TroudhuK** [apache/logging-log4cxx#233]
Hierarchy::addHierarchyEventListener allows to register a listener to intercept the appenders additions to a logger.
But there is no way to remove a listener, for example because its lifetime isn't the same as the logger (when we do it to Logger::getRootLogger()->getLoggerRepository()). True, or do I miss something?

If true, I'd like to have a Hierarchy::removeHierarchyEventListener.

**Comment by rm5248** [comment]
It looks like this was never added, since it is not part of the Log4j1 API.  It seems reasonable to add though.

**Comment by rm5248** [comment]
fixed in #234
