### ISSUE TITLE
Incorrect destructor handling in FileWatchdog causes crashes

### ISSUE THREAD

**Issue by openweed** [apache/logging-log4cxx#266]
If you change the log file before the application terminates, it may crash due to pure virtual call.

It happens because the FileWatchdog destructor works incorrectly, or rather its main function, which works in a separate thread, reacts to a stop from the destructor. When the class signals it to stop from its destructor, the destructor of the derived class has already finished its work and reset the vtable. The worker thread itself, even when receiving FileWatchdog::is_interrupted, tries to call FileWatchdog::checkAndConfigure, from within which a purely virtual function is called.

**Comment by openweed** [comment]
Judging by the code that was changed, this is a fix for another situation, probably also related to unloading, but in a different place. While sorting out this bug, I looked at the master code and the bug was still there. You can see this for yourself by looking at the [destructor code](https://github.com/apache/logging-log4cxx/blob/c8d9a6a15ae540786260503d98a20926b754a366/src/main/cpp/filewatchdog.cpp#L63) and the [worker thread functions](https://github.com/apache/logging-log4cxx/blob/c8d9a6a15ae540786260503d98a20926b754a366/src/main/cpp/filewatchdog.cpp#L120).

**Comment by openweed** [comment]
While the destructor is waiting for the thread to stop, the thread can still call the virtual function, which is illegal.

**Comment by swebb2066** [comment]
Are you calling log4cxx::LogManager::shutdown() in your application?

Calling  log4cxx::LogManager::shutdown() will stop the worker thread and thereby prevent the crash.

**Comment by openweed** [comment]
No, I hope the destructors do their job right.

**Comment by swebb2066** [comment]
To help us improve the documentation, can you tell us what log4cxx info you used when developing your app and what we should change to ensure people are using LogManager::shutdown() ?

**Comment by openweed** [comment]
The description of [PropertyConfigurator::configureAndWatch ](http://svn.apache.org/repos/asf/incubator/log4cxx/tags/v0_9_7/xdocs/www/manual/classlog4cxx_1_1PropertyConfigurator.html#e1) doesn't say anything about this. Moreover, the FileWatchdog class itself has no way to stop a thread other than by calling a destructor, and the fact that it is in a destructor means that calling the doOnChange method from any thread will crash. Therefore, I think that calling log4cxx::LogManager::shutdown() will also lead to a crash because there is a bug in FileWatchdog and the documentation will not fix it.

**Comment by swebb2066** [comment]
In the destructor code (invoked by call to `APRInitializer::unregisterAll()` in  `log4cxx::LogManager::shutdown()`)
```
FileWatchdog::~FileWatchdog()
{
	m_priv->interrupted = 0xFFFF;

	{
		std::unique_lock<std::mutex> lock(m_priv->interrupt_mutex);
		m_priv->interrupt.notify_all();
	}
	m_priv->thread.join();
}
```
simply signals the worker thread to stop. There will be no crash as the `m_priv->thread.join();` blocks until the the worker has stopped.
