### ISSUE TITLE
Build log4cxx for QNX aarch64le 

### ISSUE THREAD

**Issue by simonevallifuoco** [apache/logging-log4cxx#304]
Is it possible to build log4cxx for aarch64le platform with QNX OS? Anyone could help me?

**Comment by rm5248** [comment]
QNX is not a platform that is tested, but it should be possible to use.  As long as you have a valid C++11 compiler it should be able to be compiled.  I have used log4cxx on aarch64 before with Linux, so the architecture does not matter.

If you have a specific question with an error that you are seeing we can perhaps help with that, but otherwise we probably can't provide any general support.

**Comment by simonevallifuoco** [comment]
Thank you @rm5248.

I have a valid compiler and the cross-compilation toolchain needed. Do I have to build with CMake? If so, how do I tell it to build this project for my specific platform? I tried to build manually the project but got several issues with the dependencies (apr mainly), so I am a bit lost. How would you proceed to build for aarch64 QNX?

**Comment by swebb2066** [comment]
Cross compiling APR is a little tricky as APR use of autotools requires the configuration variables of the target (QNX in your case) system. You need to generate a configure script on a host system using:
`./configure --cache-file=QNX-aarch64le.cache`
 and then remove the 'precious' autoconf variables ( ac_cv_env_* ) from QNX-aarch64le.cache before using the crosscompiler
```
export CC=....
export CCFLAGS=...
./configure --cache-file=QNX-aarch64le.cache


```

**Comment by simonevallifuoco** [comment]
Thank you @swebb2066 

I am now trying to cross-compile log4cxx using CMake adding the correct variables for QNX and aarch64 in the main CMakeLists.txt file, but the cmake command stops with an error because it cannot find EXPAT library: 
$ cmake ..
-- The CXX compiler identification is QCC 8.3.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'apr-1'
--   Found apr-1, version 1.6.5
-- Found APR: apr-1  
-- Checking for module 'apr-util-1'
--   Found apr-util-1, version 1.6.1
-- Found APR-Util: aprutil-1;ldap;lber  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - not found
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find EXPAT (missing: EXPAT_LIBRARY) (found version "2.4.7")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindEXPAT.cmake:63 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:84 (find_package)


-- Configuring incomplete, errors occurred!


Anyone has idea why?

**Comment by swebb2066** [comment]
I find the [cmake --debug-find](https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-debug-find) introduce in cmake 3.17 helpful.

**Comment by swebb2066** [comment]
If you are able to share the QNX-aarch64le.cache that you created, I can make it avilable for others in [the conan-center-index recipe I have proposed](https://github.com/conan-io/conan-center-index/pull/17609).
