### ISSUE TITLE
FMT macros fail to build with no arguments

### ISSUE THREAD

**Issue by rm5248** [apache/logging-log4cxx#344]
I've come back to some code that I'm pretty sure worked before:

```
LOG4CXX_INFO_FMT(logger, "hello");
```

However, GCC 12.2 and clang 14 both fail to compile this code.  I'm fairly certain it compiled properly with GCC 10.2.

The problem is that in our macros we use `__VA_ARGS__` which because there are no arguments seems to cause an error in these compilers.  The workaround for now is to simply use `LOG4CXX_INFO` instead of the `_FMT` series of macros or to simply add an (unused) argument, but this seems a little silly.

It seems that with C++20, we could do `__VA_OPT__(,) __VA_ARGS__`.  Ideally we should be able to support versions before C++20 in a portable way.

Some more info:
https://stackoverflow.com/questions/5891221/variadic-macros-with-zero-arguments
https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html

**Comment by swebb2066** [comment]
Support for `LOG4CXX_INFO_FMT(logger, "hello");` was lost a side effect of improving the documentation (see 21f0f12a9bd378cb1b62c0b6218190dcf52ae938).

**Comment by rm5248** [comment]
ah.  That is unfortunate.

I think we can do two things to fix this then:

1. add a preprocessor configuration macro(`LOG4CXX_ALLOW_EMPTY_FMT` or something like that) that enables the old behavior(not used if using C++20 or newer)
2. If C++20 is detected, simply use the `__VA_OPT__(,) __VA_ARGS__` solution in the logging macro.

**Comment by rm5248** [comment]
Looking at it a bit more, the better solution may actually be:

1. For GCC/clang before C++20, use `##__VA_ARGS__`
2. For MSVC before C++20, we may be able to use `__VA_ARGS__` directly("[The traditional Microsoft C++ implementation suppresses a trailing comma if no arguments are passed to the ellipsis.](https://learn.microsoft.com/en-us/cpp/preprocessor/variadic-macros?view=msvc-170)")
3. If a different compiler, use the current behavior until somebody can provide a patch for their specific compiler.
4. If C++ 20, use the `VA_OPT` macro to align with the standard

**Comment by rm5248** [comment]
For my purposes the fix I just merged is fine, since I can upgrade to C++20(I was using C++17).

Is there anything we would like to do in order to make this possible to do in a pre-C++20 environment?
