### ISSUE TITLE
Use Logging Services common pages

### ISSUE THREAD

**Issue by vy** [apache/logging-log4cxx#370]
I have revamped the [Download](https://logging.apache.org/download.html), [Support](https://logging.apache.org/support.html), and [Security](https://logging.apache.org/security.html) pages of Logging Services (LS) such that they now cover all LS projects. In the Log4j website, I have wired all associated links to there and I have replaced all overlapping content to point to there. Would you consider implementing the following changes for the left menu of the Log4cxx website?

1. Replace _"Community"_ and all sublinks/pages under it with a _"Support"_ link pointing to the LS Support page
1. Point _"Get > Download"_ to the LS Download page
1. Add a _"Security"_ link pointing to the LS Security page

**Comment by vy** [comment]
> As far as I can see, those three pages do not seem to have anything that is relevant to a Log4cxx user.

Pages I cited are implemented in a project agnostic way. That is,

* [Download](https://logging.apache.org/download.html) points to locations where users can download artifacts **of all projects** and shows how to verify them
* [Support](https://logging.apache.org/support.html) shares official support channels, i.e., mailing lists, GitHub Discussions, GitHub Issues **of all projects**. (Search for `log4cxx` in that page for Log4cxx-specific entries.) It guides users using _any_ LS project on how to get support.
* [Security](https://logging.apache.org/security.html) page (which Log4cxx websites currently doesn't have an equivalent right now!) guides users on how to get support on security issues, and shares VDR files and CVE lists covering **all projects**.

Hence, I think the content covers all Download-Support-Security needs of LS projects, including Log4cxx. If you think something is falling short from a Log4cxx perspective, I would be more than happy to accommodate that.

Note that, yesterday [Log4net](https://logging.apache.org/log4net/) also migrated all their Download-Support-Security pages too.

> I notice the links to these pages are available from the [Apache Logging Services main page](https://logging.apache.org/). Would not that be adequate?

The goal is to

* Remove the maintenance burden of these pages for each project individually
* Create a coherent Download-Support-Security experience for users of all LS projects

Log4j, Log4j Scala, Log4j Kotlin, Log4Net, etc. all have already migrated. Log4cxx is the only project left out.

Please note that this is not a requirement. If, as the primary Log4cxx maintainer, you think you are doing just fine as it is now, it is all good, you can go ahead and close this ticket. That said, I kindly ask you to consider the arguments I raised above. (For instance, see [how I've just responded to a security inquiry today](https://lists.apache.org/thread/3tsw7mn8tbq8xy44ogsrpzbd4nwdxsy1) – you need to login with your Apache credentials to view the message.)

**Comment by swebb2066** [comment]
> Pages I cited are implemented in a project agnostic way.

They really do not read like that. They are heavily oriented towards Log4j.

> The goal is to
> 
> Remove the maintenance burden of these pages for each project individually
> Create a coherent Download-Support-Security experience for users of all LS projects

Is it not more important to be useful to the user than to "Remove the maintenance burden"? 

Does it really "Remove the maintenance burden" ?

Is "a coherent Download-Support-Security experience for users" a thing when the user is a C++/Java/C# developer?

**Comment by vy** [comment]
> > Pages I cited are implemented in a project agnostic way.
> 
> They really do not read like that. They are heavily oriented towards Log4j.

Please feel free to make changes as see fit. You have write access to the `logging-site` repository.

> > The goal is to
> > Remove the maintenance burden of these pages for each project individually
> > Create a coherent Download-Support-Security experience for users of all LS projects
> 
> Is it not more important to be useful to the user than to "Remove the maintenance burden"?

What I say is it **also** removes the maintenance burden.

> Does it really "Remove the maintenance burden" ?

Log4cxx has one website, Log4j has 6. Log4cxx doesn't even have a Security page – I hope it won't need its Log4Shell to have one. Yes, _"maintenance burden"_ is a real thing.

> Is "a coherent Download-Support-Security experience for users" a thing when the user is a C++/Java/C# developer?

I don't know where you get that impression from, but a big part of our users are **not** developers: system administrators (some without any programming background!), DevOps, etc. just trying to get the logging working, or upgraded, or patched, etc. of an application they happen to be responsible for taking care of.

**Comment by swebb2066** [comment]
> Please feel free to make changes as see fit

I am not convinced generalised documentation is good documentation so I would not be able to help.

> Log4cxx has one website, Log4j has 6

Yes, standardisation makes a lot of sense for Log4j. Adding Log4cxx and Log4Net to the coverage makes it hard to write user specific text.

**Comment by vy** [comment]
@swebb2066, [I offered you to close this ticket if you think Log4cxx is doing fine](https://github.com/apache/logging-log4cxx/issues/370#issuecomment-2071664759):

> If, as the primary Log4cxx maintainer, you think you are doing just fine as it is now, it is all good, you can go ahead and close this ticket.

you did not close the ticket. I asked you to adapt the content to your needs, you said you won't. I addressed all your arguments, you said you are not convinced. I am not able to understand how you want to proceed. Help me out, please.

**Comment by swebb2066** [comment]
Could you please discuss any future proposals for Apache Logging Services improvements on the mailing list before raising an issue in each repository. Thanks
