### ISSUE TITLE
SIGSEV in log4cxx::helpers::Class::toString()

### ISSUE THREAD

**Issue by dingetje** [apache/logging-log4cxx#420]
I have build log4cxx 1.3.0 from source using CMake on RHEL7 with devtools-11

All tests are pass, 

But when I link this log4cpp into my own shared library the application crashes immediately when I try to load my shared library in a test application:

````
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff69d5638 in log4cxx::helpers::Class::toString() const () from /home/antoinem/projects/log4cxx/apache-log4cxx-1.3.0/build/log4cxx/src/main/cpp/liblog4cxx.so.15
(gdb) info stack
#0  0x00007ffff69d5638 in log4cxx::helpers::Class::toString() const () from /home/antoinem/projects/log4cxx/apache-log4cxx-1.3.0/build/log4cxx/src/main/cpp/liblog4cxx.so.15
#1  0x00007fffee5cb863 in log4cxx::helpers::Class::registerClass (newClass=newClass@entry=0x7fffee8634f0 <log4cxx::helpers::AppenderAttachableImpl::theClassAppenderAttachableImpl>) at class.cpp:101
#2  0x00007fffee5cbad9 in log4cxx::helpers::Class::Class (this=0x7fffee8634f0 <log4cxx::helpers::AppenderAttachableImpl::theClassAppenderAttachableImpl>, name=...) at class.cpp:47
#3  0x00007fffee5c1e56 in ClassAppenderAttachableImpl (this=0x7fffee8634f0 <log4cxx::helpers::AppenderAttachableImpl::theClassAppenderAttachableImpl>) at ../include/log4cxx/helpers/appenderattachableimpl.h:46
#4  __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at appenderattachableimpl.cpp:27
#5  _GLOBAL__sub_I_appenderattachableimpl.cpp(void) () at appenderattachableimpl.cpp:143
#6  0x00007ffff7dea9c3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#7  0x00007ffff7def59e in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#8  0x00007ffff7dea7d4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#9  0x00007ffff7deeb8b in _dl_open () from /lib64/ld-linux-x86-64.so.2
#10 0x00007ffff7bd7fab in dlopen_doit () from /lib64/libdl.so.2
#11 0x00007ffff7dea7d4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#12 0x00007ffff7bd85ad in _dlerror_run () from /lib64/libdl.so.2
#13 0x00007ffff7bd8041 in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
#14 0x0000000000400719 in main () at main.cpp:9
(gdb)
 ````

**Comment by dingetje** [comment]
Is this due to static initialization order fiasco?

**Comment by dingetje** [comment]
I've build using static APR and APU libraries because there are already older versions installed:

````
~/projects/cmake/cmake-3.13.5-Linux-x86_64/bin/cmake -B build/log4cxx -DAPR_STATIC=yes -DAPU_STATIC=yes -DCMAKE_PREFIX_PATH=$HOME/libraries -DCMAKE_INSTALL_PREFIX=$HOME/Libraries -DBUILD_SHARED_LIBS=off -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-11/root/usr/bin/g++ -DCMAKE_C_COMPILER=/opt/rh/devtoolset-11/root/usr/bin/gcc
-- The CXX compiler identification is GNU 11.2.1
-- Check for working CXX compiler: /opt/rh/devtoolset-11/root/usr/bin/g++
-- Check for working CXX compiler: /opt/rh/devtoolset-11/root/usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found APR: /home/antoinem/libraries/lib/libapr-1.a  
-- Found APR-Util: /home/antoinem/libraries/lib/libaprutil-1.a  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found EXPAT: /usr/lib64/libexpat.so (found version "2.1.0") 
-- Looking for C++ include locale
-- Looking for C++ include locale - found
-- Looking for mbsrtowcs
-- Looking for mbsrtowcs - found
-- Looking for wcstombs
-- Looking for wcstombs - found
-- Looking for fwide
-- Looking for fwide - found
-- Looking for syslog
-- Looking for syslog - found
-- Looking for pthread_sigmask
-- Looking for pthread_sigmask - found
-- Looking for pthread_self
-- Looking for pthread_self - found
-- 
-- 
-- log4cxx configuration summary:
-- 
--   C++ compiler .................... : /opt/rh/devtoolset-11/root/usr/bin/g++
--   C++ features requested: ......... : 20
--   Build shared library ............ : off
--   Build tests ..................... : ON
--   Build examples................... : ON
--   Build fuzzers.................... : OFF
--   Build site ...................... : OFF
--   Install prefix .................. : /home/antoinem/Libraries
--   log4cxx library name ............ : log4cxx
--   log4cxx namespace ............... : log4cxx
--   log4cxx char API ................ : ON
--   log4cxx wchar API ............... : ON
--   log4cxx unichar API ............. : OFF
--   log4cxx char type ............... : utf-8
--   character encoding .............. : utf-8
--   Networking support .............. : ON
--   DOMConfigurator support ......... : ON
--   Qt support ...................... : OFF
-- C++ version and Boost settings:
--   Prefer boost: ................... : OFF
--   make_unique implementation :..... : std::make_unique
--   filesystem implementation ....... : std::filesystem
--   format implementation ........... : fmt::format
--   thread_local support? ........... : TRUE
-- Applications required for tests:
--   zip ............................. : /bin/zip
--   sed ............................. : /bin/sed
--   gzip ............................ : /bin/gzip
-- Available appenders:
--   Async Appender .................. : ON
--   ODBC Appender ................... : OFF
--   DB Appender ..................... : ON
--   SMTP Appender ................... : OFF
--   XMLSocketAppender ............... : ON
--   SocketHubAppender ............... : ON
--   SyslogAppender .................. : ON
--   Using syslog.h .................. : ON
--   TelnetAppender .................. : ON
--   NTEventLogAppender .............. : OFF
--   OutputDebugStringAppender ....... : ON
--   ConsoleAppender ................. : ON
--   FileAppender .................... : ON
--   RollingFileAppender ............. : ON
--   MultiprocessRollingFileAppender . : OFF
-- Available layouts:
--   HTMLLayout ...................... : ON
--   JSONLayout ...................... : ON
--   PatternLayout ................... : ON
--   SimpleLayout .................... : ON
--   XMLLayout ....................... : ON
--   FMTLayout ....................... : OFF
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_C_COMPILER


-- Build files have been written to: /home/antoinem/projects/log4cxx/apache-log4cxx-1.3.0/build/log4cxx
````

**Comment by dingetje** [comment]
With the shared log4cxx library, all tests are pass.

The SIGSEV still happens though, so I'm at a loss

**Comment by rm5248** [comment]
Line 101 is [the definition of the function](https://github.com/apache/logging-log4cxx/blob/0ff3c8a454bd2de1bd911293af8febe42ab25b70/src/main/cpp/class.cpp#L101), which is odd.  My best guess is that the reason it says that line is segfaulting is due to a mismatch between the C++ library that log4cxx was compiled with and the library it is running with.

libstdc++ is generally stable between versions with backwards compatibility, but probably some part of the definition of `std::string` changed between the versions.

Some things to try:

1. Force C++11 with `-DCMAKE_CXX_STANDARD=11`
2. Use an older compiler(e.g. the one that libstdc++ was compiled with)
3. Check to see when g++ is running which version of libstdc++ it is using, if it is the one bundled with the compiler or the one on the system

**Comment by swebb2066** [comment]
> #0  0x00007ffff69d5638 in log4cxx::helpers::Class::toString() const () from /home/antoinem/projects/log4cxx/apache-log4cxx-1.3.0/build/log4cxx/src/main/cpp/liblog4cxx.so.15

The function `Class::toString()` is not called from `Class::registerClass` in the current code base. A Jan 2005 (commit c697bcda40461c33b0ff2411307823be05a63204) replaced that call with a call to `Class::getName`.

Somehow you seem to be using an old version of the code.

**Comment by swebb2066** [comment]
> The static build of log4cxx crashed on 3 tests:

I guess the code you are building has a modified class.cpp (based on a version from 2004) where the modification adds some registerClass() calls for your extension classes. I would instead suggest you build a [shared library containing just your extensions](https://logging.apache.org/log4cxx/1.3.0/extending-log4cxx.html) and load that shared library before you load the Log4cxx configuration.

**Comment by dingetje** [comment]
I cannot use an older compiler, the current source code of log4cxx will not compile with the stock RHEL7 gcc compiler (which is `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)`)

I'm also not using old code, this is a fresh download of the 1.3.0 tarball of log4cxx, but having said that, there's a legacy log4cxx based on 0.9.7 installed that may get loaded before the new version that could be causing this.
When I run ldd on my shared library build it references that old library too.

````
[antoinem@smt8-01 exalib]$ ldd libcifset-EL7-64bit.so | grep liblog
        liblog4cxx.so.15 => /home/antoinem/projects/log4cxx/apache-log4cxx-1.3.0/build/log4cxx/src/main/cpp/liblog4cxx.so.15 (0x00007f76ec81d000)
        liblog4cxx.so.9 => /opt/hp93000rt/el7/x86_64/log4cxx_0.9.7/lib/liblog4cxx.so.9 (0x00007f76e3424000)
````

I'm afraid there's not much I can do to prevent this, since the environment I need to run in is not under my control.

**Comment by dingetje** [comment]
Thanks guys, I'll close this issue.

**Comment by rm5248** [comment]
> ```
> [antoinem@smt8-01 exalib]$ ldd libcifset-EL7-64bit.so | grep liblog
>         liblog4cxx.so.15 => /home/antoinem/projects/log4cxx/apache-log4cxx-1.3.0/build/log4cxx/src/main/cpp/liblog4cxx.so.15 (0x00007f76ec81d000)
>         liblog4cxx.so.9 => /opt/hp93000rt/el7/x86_64/log4cxx_0.9.7/lib/liblog4cxx.so.9 (0x00007f76e3424000)
> ```

This looks to me like when you're building the shared library, you're somehow linking to log4cxx twice.  Perhaps there is a transitive dependency on log4cxx from another library?  I'm not quite sure what the behavior would be when this runs, but I suspect that the symbols may be loaded in an indeterminate way, some from one library and some from another.

One thing you could try in this case would be to configure the build and have a custom namespace, e.g. `-DLOG4CXX_NS=new_log4cxx`.  You would need to change your code to use the new namespace if you do this.
