### ISSUE TITLE
[Feature request] Please add vcpkg feature to enable Qt support

### ISSUE THREAD

**Issue by JoeyJoeJoeJrShabadoo** [apache/logging-log4cxx#423]
Hi everybody, first thanks a lot for your effort to maintain this terrific piece of software.

There's one thing I'd love to have in addition: Would it be possible to add a feature to the vcpkg port that enables the Qt support (LOG4CXX_QT_SUPPORT=ON)? I tried myself, but failed. What I mean is, if using vcpkg in manifest mode, it should be possible to do this in the vcpkg.json:

```
{
  "dependencies": [
    {
      "name": "log4cxx",
      "features": [ "qtsupport" ]
    } 
  ]
}
```
In my imagination, this would add LOG4CXX_QT_SUPPORT=ON to the build flags and do whatever else it needs to make things work automagically.

Thanks for considering.

**Comment by swebb2066** [comment]
Thank you. I am happy you find the library useful.

I added a [PR to vcpkg](https://github.com/microsoft/vcpkg/pull/41928)

**Comment by JoeyJoeJoeJrShabadoo** [comment]
Wow, that was pretty quick, thank you very much, Stephen. As a additional benefit I can see now what I was missing when trying myself 👍 
I'll wait till the PR is merged and close the issue then.

**Comment by rm5248** [comment]
should we also update the vcpkg version to 1.3.0?  Although perhaps that should be a separate PR.

**Comment by JoeyJoeJoeJrShabadoo** [comment]
Sounds reasonable to me.

**Comment by swebb2066** [comment]
I have already [created a PR to update to 1.3.0](https://github.com/microsoft/vcpkg/pull/41927), but installing pkg_config files breaks vcpkg.

I think we will need to add a cmake option for pkg_config so pkf_config file installation can be switched off in vcpkg

**Comment by JoeyJoeJoeJrShabadoo** [comment]
Closing the issue as completed. Thank you for the implementation, I appreciate it.
