### ISSUE TITLE
[Feature Request]: ECS compliant logs support in log4cxx

### ISSUE THREAD

**Issue by rkay-dev** [apache/logging-log4cxx#428]
Hi, I  would like to propose a feature request to add a layout to support ecs compliant logs just like the ecsencoder in java. Is there any task in progress for this or is it in the coming milestones?

**Comment by rm5248** [comment]
There is noting currently in progress for ECS logs, as it is not a feature that anybody has asked for.

If you are interested in trying to add it yourself, take a look at the [JSONLayout](https://github.com/apache/logging-log4cxx/blob/3aa883c5da7784e21bde320a13498a05104658bc/src/main/cpp/jsonlayout.cpp) class that already exists.

**Comment by rkay-dev** [comment]
> There is noting currently in progress for ECS logs, as it is not a feature that anybody has asked for.
> 
> If you are interested in trying to add it yourself, take a look at the [JSONLayout](https://github.com/apache/logging-log4cxx/blob/3aa883c5da7784e21bde320a13498a05104658bc/src/main/cpp/jsonlayout.cpp) class that already exists.

okay. i have written one such layout myself to use in one of my projects. thought that it would enhance the robustness of the library.
